HARIPRASAD SIVAPATHAM ANAND 

X2022gmv

In [117]:
import pandas as pd
import numpy as np 
from sklearn.ensemble import GradientBoostingClassifier

In [118]:
auc_values = pd.read_csv("./AUC_VALUES.csv")

In [119]:
auc_values

             Columns  AUC_VALUES
0           Assay_Id    0.854496
1       BCUT2D_CHGHI    0.791767
2        BCUT2D_MRHI    0.791709
3      BCUT2D_LOGPHI    0.791671
4       BCUT2D_CHGLO    0.791207
..               ...         ...
204       SlogP_VSA9    0.500000
205         fr_diazo    0.500000
206  fr_prisulfonamd    0.500000
207         SMR_VSA8    0.500000
208      fr_barbitur    0.500000

[209 rows x 2 columns]

In [120]:
# Chosing Columns with AUC greater than 0.7

In [121]:
required_columns = []
for index,row in auc_values.iterrows():
    if(row["AUC_VALUES"]>0.75):
        required_columns.append(row["Columns"])

In [122]:
train_data = pd.read_csv("./detail_smile_data_train.csv")

In [125]:
required_columns

['Assay_Id',
 'BCUT2D_CHGHI',
 'BCUT2D_MRHI',
 'BCUT2D_LOGPHI',
 'BCUT2D_CHGLO',
 'Chi2v',
 'BCUT2D_MRLOW',
 'BCUT2D_LOGPLOW',
 'Chi3v',
 'Chi2n',
 'BCUT2D_MWLOW',
 'MaxAbsEStateIndex',
 'MaxEStateIndex',
 'Chi3n',
 'Chi1v',
 'Chi4v',
 'qed',
 'Chi4n',
 'Chi1n',
 'MolMR',
 'MolLogP',
 'BertzCT',
 'MinEStateIndex',
 'Chi0v',
 'LabuteASA',
 'Kappa3',
 'Chi0n',
 'MinAbsPartialCharge',
 'MaxPartialCharge',
 'MinAbsEStateIndex',
 'Kappa2',
 'ExactMolWt',
 'MolWt',
 'MinPartialCharge',
 'MaxAbsPartialCharge',
 'BalabanJ',
 'Kappa1',
 'Ipc']

In [92]:
train_data

,MaxEStateIndex,MinEStateIndex,MaxAbsEStateIndex,MinAbsEStateIndex,qed,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,NumRadicalElectrons,...,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea,Assay_Id,label
0,9.316200,-1.533785,9.316200,0.150485,0.794714,317.599,306.511,315.982463,100,0,...,0,0,0,0,0,0,0,0,1644,2
1,10.532611,0.333788,10.532611,0.333788,0.516641,156.269,136.109,156.151415,66,0,...,0,0,0,0,0,0,4,0,2451,2
2,2.433032,0.000000,2.433032,0.000000,0.251327,362.086,313.702,361.347528,148,0,...,0,0,0,0,0,0,12,0,1384,2
3,10.355080,-0.613825,10.355080,0.282361,0.487998,255.665,245.585,255.052302,90,0,...,0,0,0,0,0,0,0,0,16,2
4,0.000000,0.000000,0.000000,0.000000,0.237972,149.894,149.894,149.894242,8,0,...,0,0,0,0,0,0,0,0,1856,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75378,11.460021,-3.868472,11.460021,0.053611,0.712426,230.245,220.165,230.036128,82,0,...,0,0,0,0,0,0,0,0,33,2
75379,5.928972,-2.841623,5.928972,0.082346,0.720533,313.747,296.611,313.041677,104,0,...,0,0,0,0,0,0,0,0,1632,1
75380,4.975926,0.848333,4.975926,0.848333,0.596343,167.258,162.218,166.986341,50,0,...,0,0,0,1,0,0,0,0,1373,1
75381,10.241948,0.324028,10.241948,0.324028,0.519485,128.215,112.087,128.120115,54,0,...,0,0,0,0,0,0,0,0,2,2
75382,12.552405,-0.188577,12.552405,0.048913,0.165457,636.962,572.450,636.486608,258,0,...,0,0,0,0,0,0,5,0,2,1

In [93]:
for col in train_data:
    mean = train_data[col].mean()
    train_data[col] = train_data[col].fillna(mean)

In [94]:
train_data

,MaxEStateIndex,MinEStateIndex,MaxAbsEStateIndex,MinAbsEStateIndex,qed,MolWt,HeavyAtomMolWt,ExactMolWt,NumValenceElectrons,NumRadicalElectrons,...,fr_sulfone,fr_term_acetylene,fr_tetrazole,fr_thiazole,fr_thiocyan,fr_thiophene,fr_unbrch_alkane,fr_urea,Assay_Id,label
0,9.316200,-1.533785,9.316200,0.150485,0.794714,317.599,306.511,315.982463,100,0,...,0,0,0,0,0,0,0,0,1644,2
1,10.532611,0.333788,10.532611,0.333788,0.516641,156.269,136.109,156.151415,66,0,...,0,0,0,0,0,0,4,0,2451,2
2,2.433032,0.000000,2.433032,0.000000,0.251327,362.086,313.702,361.347528,148,0,...,0,0,0,0,0,0,12,0,1384,2
3,10.355080,-0.613825,10.355080,0.282361,0.487998,255.665,245.585,255.052302,90,0,...,0,0,0,0,0,0,0,0,16,2
4,0.000000,0.000000,0.000000,0.000000,0.237972,149.894,149.894,149.894242,8,0,...,0,0,0,0,0,0,0,0,1856,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75378,11.460021,-3.868472,11.460021,0.053611,0.712426,230.245,220.165,230.036128,82,0,...,0,0,0,0,0,0,0,0,33,2
75379,5.928972,-2.841623,5.928972,0.082346,0.720533,313.747,296.611,313.041677,104,0,...,0,0,0,0,0,0,0,0,1632,1
75380,4.975926,0.848333,4.975926,0.848333,0.596343,167.258,162.218,166.986341,50,0,...,0,0,0,1,0,0,0,0,1373,1
75381,10.241948,0.324028,10.241948,0.324028,0.519485,128.215,112.087,128.120115,54,0,...,0,0,0,0,0,0,0,0,2,2
75382,12.552405,-0.188577,12.552405,0.048913,0.165457,636.962,572.450,636.486608,258,0,...,0,0,0,0,0,0,5,0,2,1

In [95]:
X = train_data[required_columns]
y = train_data["label"]

In [107]:
model = GradientBoostingClassifier()

In [108]:
model.fit(X,y)

GradientBoostingClassifier()

In [109]:
test_data = pd.read_csv("./detail_smile_data_test.csv")

In [110]:
test_data_clean = pd.read_csv("./data/test_data_new")

In [111]:
test_data["Assay_Id"] = test_data_clean.assay_ids

In [112]:
for col in test_data:
    mean = test_data[col].mean()
    test_data[col] =  test_data[col].fillna(mean)

In [113]:
predict = model.predict(test_data[required_columns])

In [114]:
sub_file = pd.read_csv("./data/sample_submission.csv")

In [115]:
sub_file["Predicted"] = predict

In [116]:
sub_file.to_csv("Submission_31_jan_4.csv",index=False)